### ISSUE TITLE
bug(authentification): can't login or join

### ISSUE THREAD

**Issue by Kristinita** [1self/website#7]
### 1. Summary

I can't login on **<http://www.1self.co/>** site.

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN
+ Browsers:

    + Firefox Quantum 59.0.2 (64-bit)
    + Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### 3. Steps to reproduce

I visit **<http://www.1self.co/>** →

1. I press to `LOG IN` button
1. I press `JOIN` button → I wrote `SashaChernykh` username → `Join using GitHub`

### 4. Expected behavior

Successful authorization in both cases.

### 5. Actual behavior

In browser open page with stack trace:

```node
Not Found
404

Error: Not Found
    at /opt/cardapp/app.js:77:15
    at Layer.handle [as handle_request] (/opt/cardapp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/cardapp/node_modules/express/lib/router/index.js:312:13)
    at /opt/cardapp/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/cardapp/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/cardapp/node_modules/express/lib/router/index.js:271:10)
    at /opt/cardapp/node_modules/express/lib/router/index.js:618:15
    at next (/opt/cardapp/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/opt/cardapp/node_modules/express/lib/router/index.js:176:3)
    at router (/opt/cardapp/node_modules/express/lib/router/index.js:46:12)
```

Thanks.

**Comment by edsykes** [comment]
Hi, thanks for taking the time to log a very detailed bug report!

We're no longer developing 1self and have shut the app down. We'll tidy the web site up as soon as possible to remove the login button.
